### ISSUE TITLE
test failure: TestResumeFromCheckpointE2EWithManualSentinel

### ISSUE THREAD

**Issue by jayjanssen** [cashapp/spirit#320] opened 2024-07-01 14:38 UTC
Sometimes the test `TestResumeFromCheckpointE2EWithManualSentinel` errors with:
```
    runner_test.go:2666: 
        	Error Trace:	/home/runner/work/spirit/spirit/pkg/migration/runner_test.go:2666
        	            				/opt/hostedtoolcache/go/1.22.4/x64/src/runtime/asm_amd64.s:1695
        	Error:      	Error "sql: database is closed" does not contain "context canceled"
        	Test:       	TestResumeFromCheckpointE2EWithManualSentinel
```

**Comment by morgo** [comment] 2024-07-01 17:55
Duplicate of https://github.com/cashapp/spirit/issues/315

**Closed** 2024-09-04 14:21 UTC
